import json
import stripe
import logging
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils import timezone
from django.contrib import messages
from ipware import get_client_ip

from .models import UserProfile, UploadRecord, AnonymousUploadRecord

stripe.api_key = settings.STRIPE_SECRET_KEY
logger = logging.getLogger(__name__)


# ── Helpers ─────────────────────────────────────────────────────

# def get_client_ip(request):
#     x_forwarded = request.META.get('HTTP_X_FORWARDED_FOR')
#     if x_forwarded:
#         return x_forwarded.split(',')[0].strip()
#     return request.META.get('REMOTE_ADDR', '0.0.0.0')


def get_or_create_profile(user):
    profile, _ = UserProfile.objects.get_or_create(user=user)
    return profile


# ── Public pages ────────────────────────────────────────────────

def landing(request):
    if request.user.is_authenticated:
        return redirect('dashboard')

    faqs = [
        {"q": "Do you store my PDF files?", "a": "No. Your PDF is sent to our server only to extract headings and check file size. The file is never saved to disk or a database. The actual TOC generation and editing happens entirely in your browser using pdf-lib."},
        {"q": "What happens to my data?", "a": "We store only your email address, plan details, and upload metadata (filename, size, timestamp) for rate-limiting purposes. No file content is ever stored."},
        {"q": "Can I use it without signing up?", "a": "Yes! Guest users can upload files up to 5 MB, once per day, with a watermark on the exported PDF. Sign up for free to get 10 MB and 5 uploads per day."},
        {"q": "What does 'watermarked' mean?", "a": "Free and guest-tier exports include a faint diagonal watermark on the TOC page reading 'GENERATED BY TOC GENERATOR'. Pro and Premium users get completely clean exports."},
        {"q": "How does the TOC extraction work?", "a": "We first check the PDF for an existing document outline (bookmarks). If found, those are used directly. Otherwise, we analyse font sizes to automatically detect headings. You can always edit, reorder, or add entries manually."},
        {"q": "Can I reorder or remove pages?", "a": "Yes — the Pages tab in the editor lets you drag pages into any order, remove pages from the export, and control exactly where the TOC page is inserted."},
        {"q": "How do I cancel my subscription?", "a": "From your dashboard, click 'Manage subscription' to open the Stripe Customer Portal, where you can cancel, pause, or change your plan at any time. You keep access until the end of your billing period."},
        {"q": "What payment methods are accepted?", "a": "All major credit and debit cards (Visa, Mastercard, Amex) via Stripe. Stripe is PCI-compliant and we never see or store your card details."},
        {"q": "Is there a free trial for Pro/Premium?", "a": "We don't currently offer a trial period, but the free tier gives you a good sense of the tool. You can upgrade and cancel at any time."},
    ]

    return render(request, 'core/landing.html', {
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY,
        'plan_limits': settings.PLAN_LIMITS,
        'faqs': faqs,
    })


# ── Dashboard ────────────────────────────────────────────────────

@login_required
def dashboard(request):
    profile = get_or_create_profile(request.user)
    uploads_today = profile.uploads_today()
    limits = profile.limits
    plan = profile.effective_plan

    return render(request, 'core/dashboard.html', {
        'profile': profile,
        'plan': plan,
        'limits': limits,
        'uploads_today': uploads_today,
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY,
        'recent_uploads': request.user.uploads.all()[:10],
    })


# ── Upload / process API ─────────────────────────────────────────

def upload_pdf(request):
    """
    Accepts a PDF, runs the heading-extraction logic, returns JSON.
    No file is stored. We only record metadata for rate-limiting.
    """
    if request.method != 'POST':
        return JsonResponse({'error': 'POST required'}, status=405)

    pdf_file = request.FILES.get('pdf')
    if not pdf_file:
        return JsonResponse({'error': 'No file provided'}, status=400)

    file_size = pdf_file.size

    # ── Determine plan & enforce limits ──────────────────────────
    if request.user.is_authenticated:
        profile = get_or_create_profile(request.user)
        plan = profile.effective_plan
        limits = profile.limits

        max_bytes = limits['max_mb'] * 1024 * 1024
        if file_size > max_bytes:
            return JsonResponse({'error': f"File exceeds {limits['max_mb']} MB limit for your plan."}, status=400)

        if limits['daily_uploads'] is not None:
            if profile.uploads_today() >= limits['daily_uploads']:
                return JsonResponse({'error': f"Daily upload limit of {limits['daily_uploads']} reached. Upgrade for more."}, status=429)

        watermark = limits['watermark']

        # Record upload (metadata only, no file stored)
        UploadRecord.objects.create(
            user=request.user,
            filename=pdf_file.name[:255],
            file_size=file_size,
        )

    else:
        # Anonymous user
        plan_limits = settings.PLAN_LIMITS['anonymous']
        max_bytes = plan_limits['max_mb'] * 1024 * 1024
        if file_size > max_bytes:
            return JsonResponse({'error': f"File exceeds {plan_limits['max_mb']} MB limit. Sign up for more."}, status=400)

        ip, _ = get_client_ip(request)
        today = timezone.now().date()
        anon_count = AnonymousUploadRecord.objects.filter(ip_address=ip, created_at__date=today).count()
        if anon_count >= plan_limits['daily_uploads']:
            return JsonResponse({'error': 'Daily limit reached. Sign up for free to get 5 uploads/day.'}, status=429)

        AnonymousUploadRecord.objects.create(ip_address=ip)
        watermark = plan_limits['watermark']
        plan = 'anonymous'

    # ── Extract headings from PDF ─────────────────────────────────
    try:
        headings, has_outline = extract_headings(pdf_file)
    except Exception as e:
        logger.exception("PDF extraction error")
        return JsonResponse({'error': 'Could not read PDF: ' + str(e)}, status=400)

    return JsonResponse({
        'headings': headings,
        'has_outline': has_outline,
        'watermark': watermark,
        'plan': plan,
    })


def editor(request):
    """Serve the standalone in-browser PDF editor."""
    return render(request, 'core/editor.html')


def extract_headings(pdf_file):
    """
    Extract headings from a PDF using PyMuPDF (fitz) if available,
    falling back to a simple font-size heuristic with pypdf.
    Returns (headings_list, has_outline).
    """
    pdf_bytes = pdf_file.read()
    headings = []
    has_outline = False

    try:
        import fitz  # PyMuPDF
        doc = fitz.open(stream=pdf_bytes, filetype='pdf')

        # Try document outline (bookmarks) first
        toc = doc.get_toc()
        if toc:
            has_outline = True
            for item in toc:
                level, title, page = item[0], item[1], item[2]
                if title.strip() and page > 0:
                    headings.append({'title': title.strip(), 'page': page, 'level': min(level, 4)})
            doc.close()
            return headings, has_outline

        # Fallback: font-size heuristic
        font_sizes = {}
        page_spans = []
        for page_num in range(len(doc)):
            page = doc[page_num]
            blocks = page.get_text("dict", flags=16)["blocks"]
            for block in blocks:
                for line in block.get("lines", []):
                    for span in line.get("spans", []):
                        size = round(span["size"])
                        text = span["text"].strip()
                        if text and len(text) > 2:
                            font_sizes[size] = font_sizes.get(size, 0) + 1
                            page_spans.append((page_num + 1, size, text, span.get("flags", 0)))

        doc.close()
        if not font_sizes:
            return [], False

        # Sizes above median are likely headings
        sorted_sizes = sorted(font_sizes.keys(), reverse=True)
        body_size = sorted(font_sizes.keys(), key=lambda s: font_sizes[s], reverse=True)[0]

        heading_sizes = [s for s in sorted_sizes if s > body_size * 1.05][:4]
        if not heading_sizes:
            return [], False

        size_to_level = {s: i + 1 for i, s in enumerate(sorted(heading_sizes, reverse=True))}

        seen = set()
        for page_num, size, text, flags in page_spans:
            if size in size_to_level and len(text) > 3:
                key = (text[:60], page_num)
                if key not in seen:
                    seen.add(key)
                    headings.append({
                        'title': text[:120],
                        'page': page_num,
                        'level': size_to_level[size],
                    })

        return headings, False

    except ImportError:
        pass

    # Final fallback: pypdf
    try:
        from pypdf import PdfReader
        import io
        reader = PdfReader(io.BytesIO(pdf_bytes))

        # Try outline
        if reader.outline:
            has_outline = True
            def walk(items, level=1):
                for item in items:
                    if isinstance(item, list):
                        walk(item, level + 1)
                    else:
                        try:
                            page_num = reader.get_destination_page_number(item) + 1
                            headings.append({
                                'title': str(item.title).strip(),
                                'page': page_num,
                                'level': min(level, 4),
                            })
                        except Exception:
                            pass
            walk(reader.outline)
            return headings, has_outline

        # No outline — return empty with note
        return [], False

    except Exception as e:
        raise RuntimeError(f"Could not parse PDF: {e}")


# ── Stripe checkout ──────────────────────────────────────────────

@login_required
@require_POST
def create_checkout_session(request):
    plan = request.POST.get('plan')
    if plan not in settings.STRIPE_PRICES:
        return JsonResponse({'error': 'Invalid plan'}, status=400)

    price_id = settings.STRIPE_PRICES[plan]
    if not price_id:
        return JsonResponse({'error': 'Stripe price not configured. Add STRIPE_PRICE_PRO / STRIPE_PRICE_PREMIUM to .env'}, status=400)

    profile = get_or_create_profile(request.user)

    # Create or reuse Stripe customer
    if not profile.stripe_customer_id:
        customer = stripe.Customer.create(
            email=request.user.email,
            metadata={'user_id': request.user.id},
        )
        profile.stripe_customer_id = customer.id
        profile.save()

    try:
        session = stripe.checkout.Session.create(
            customer=profile.stripe_customer_id,
            payment_method_types=['card'],
            line_items=[{'price': price_id, 'quantity': 1}],
            mode='subscription',
            success_url=request.build_absolute_uri('/dashboard/?checkout=success'),
            cancel_url=request.build_absolute_uri('/dashboard/?checkout=cancelled'),
        )
        return JsonResponse({'url': session.url})
    except stripe.error.StripeError as e:
        logger.error("Stripe checkout error: %s", e)
        return JsonResponse({'error': str(e)}, status=400)


@login_required
@require_POST
def create_portal_session(request):
    profile = get_or_create_profile(request.user)
    if not profile.stripe_customer_id:
        messages.error(request, 'No billing account found.')
        return redirect('dashboard')

    try:
        session = stripe.billing_portal.Session.create(
            customer=profile.stripe_customer_id,
            return_url=request.build_absolute_uri('/dashboard/'),
        )
        return redirect(session.url)
    except stripe.error.StripeError as e:
        logger.error("Stripe portal error: %s", e)
        messages.error(request, 'Could not open billing portal: ' + str(e))
        return redirect('dashboard')


# ── Stripe webhook ───────────────────────────────────────────────

@csrf_exempt
@require_POST
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META.get('HTTP_STRIPE_SIGNATURE', '')
    webhook_secret = settings.STRIPE_WEBHOOK_SECRET

    try:
        if webhook_secret:
            event = stripe.Webhook.construct_event(payload, sig_header, webhook_secret)
        else:
            event = stripe.Event.construct_from(json.loads(payload), stripe.api_key)
    except (ValueError, stripe.error.SignatureVerificationError) as e:
        logger.warning("Webhook signature error: %s", e)
        return HttpResponse(status=400)

    _handle_stripe_event(event)
    return HttpResponse(status=200)


def _handle_stripe_event(event):
    data = event['data']['object']

    if event['type'] == 'customer.subscription.created':
        _sync_subscription(data)
    elif event['type'] == 'customer.subscription.updated':
        _sync_subscription(data)
    elif event['type'] == 'customer.subscription.deleted':
        _cancel_subscription(data)
    elif event['type'] == 'invoice.payment_failed':
        customer_id = data.get('customer')
        _update_subscription_status(customer_id, 'past_due')


def _sync_subscription(subscription):
    customer_id = subscription['customer']
    status = subscription['status']
    sub_id = subscription['id']

    try:
        profile = UserProfile.objects.get(stripe_customer_id=customer_id)
    except UserProfile.DoesNotExist:
        logger.warning("No profile for Stripe customer %s", customer_id)
        return

    profile.stripe_subscription_id = sub_id
    profile.subscription_status = status

    # Determine plan from price
    items = subscription.get('items', {}).get('data', [])
    if items:
        price_id = items[0]['price']['id']
        for plan_name, configured_price in settings.STRIPE_PRICES.items():
            if price_id == configured_price:
                profile.plan = plan_name
                break

    # Set subscription end date
    current_period_end = subscription.get('current_period_end')
    if current_period_end:
        profile.subscription_end = timezone.datetime.fromtimestamp(
            current_period_end, tz=timezone.utc
        )

    profile.save()
    logger.info("Synced subscription %s for %s → %s", sub_id, profile.user.email, profile.plan)


def _cancel_subscription(subscription):
    customer_id = subscription['customer']
    try:
        profile = UserProfile.objects.get(stripe_customer_id=customer_id)
        profile.plan = 'free'
        profile.subscription_status = 'canceled'
        profile.stripe_subscription_id = ''
        profile.save()
        logger.info("Canceled subscription for %s", profile.user.email)
    except UserProfile.DoesNotExist:
        pass


def _update_subscription_status(customer_id, status):
    try:
        profile = UserProfile.objects.get(stripe_customer_id=customer_id)
        profile.subscription_status = status
        profile.save()
    except UserProfile.DoesNotExist:
        pass


# ── Password change override ─────────────────────────────────────────────────
# allauth 0.57+ bundles its own templates that take priority even with custom
# loaders. We override the URL before allauth.urls and render our own template
# explicitly, using allauth's form and adapter so all logic stays intact.

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages as django_messages

@login_required
def password_change(request):
    from allauth.account.forms import ChangePasswordForm
    from allauth.account.adapter import get_adapter

    if request.method == 'POST':
        form = ChangePasswordForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            get_adapter(request).add_message(
                request,
                django_messages.SUCCESS,
                'account/messages/password_changed.txt',
            )
            return redirect('dashboard')
    else:
        form = ChangePasswordForm(user=request.user)

    return render(request, 'account/password_change.html', {'form': form})


# ── Social account view overrides ────────────────────────────────────────────

@login_required
def social_connections(request):
    from allauth.socialaccount.forms import DisconnectForm
    if request.method == 'POST':
        form = DisconnectForm(request.POST, request=request)
        if form.is_valid():
            form.save()
            from django.contrib import messages as django_messages
            django_messages.success(request, 'Social account disconnected.')
            return redirect('socialaccount_connections')
    else:
        form = DisconnectForm(request=request)
    return render(request, 'socialaccount/connections.html', {'form': form})


def social_login_cancelled(request):
    return render(request, 'socialaccount/login_cancelled.html')


def social_authentication_error(request):
    return render(request, 'socialaccount/authentication_error.html')


# ── Password reset override ───────────────────────────────────────────────────

def password_reset(request):
    from allauth.account.forms import ResetPasswordForm
    from allauth.account.adapter import get_adapter
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            form.save(request)
            return redirect('account_reset_password_done')
    else:
        form = ResetPasswordForm()
    return render(request, 'account/password_reset.html', {'form': form})


def password_reset_done(request):
    return render(request, 'account/password_reset_done.html')


# ── Password reset from key (the link in the email) ──────────────────────────

from allauth.account.views import PasswordResetFromKeyView as _PasswordResetFromKeyView

class CustomPasswordResetFromKeyView(_PasswordResetFromKeyView):
    template_name = 'account/password_reset_from_key.html'
    # allauth 0.57+ uses template_name_done for the success state
    template_name_done = 'account/password_reset_from_key_done.html'

password_reset_from_key = CustomPasswordResetFromKeyView.as_view()


def password_reset_from_key_done(request):
    return render(request, 'account/password_reset_from_key_done.html')